name: Sync to Public Repo

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout private repo
        uses: actions/checkout@v3

      - name: Checkout public repo
        uses: actions/checkout@v3
        with:
          repository: lenijer/DnD-sheets-Public
          token: ${{ secrets.PRIVATE_TOKEN }}
          path: public-repo

      - name: Copy files to public repo
        run: |
          rsync -av --delete --exclude='.git' --ignore-missing-args ./ ./public-repo/ || true

      - name: Commit and push changes
        working-directory: public-repo
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"

          if [[ `git status --porcelain` ]]; then
            git add .
            git commit -m "Sync from private repo"
            git push
          else
            echo "No changes to commit"
          fi